# Default directories to exclude from indexing
DEFAULT_EXCLUDED_DIRS: frozenset[str] = frozenset({
    ".git",
    ".svn",
    ".hg",
    ".bzr",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".tox",
    ".nox",
    ".venv",
    "venv",
    "env",
    ".env",
    "node_modules",
    "bower_components",
    ".next",
    ".nuxt",
    "dist",
    "build",
    "out",
    "target",
    ".gradle",
    ".idea",
    ".vscode",
    ".DS_Store",
    "coverage",
    ".coverage",
    "htmlcov",
    ".eggs",
    "*.egg-info",
    "__snapshots__",
})

# Default file patterns to exclude
DEFAULT_EXCLUDED_FILES: frozenset[str] = frozenset({
    ".gitignore",
    ".gitattributes",
    ".editorconfig",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Pipfile.lock",
    "poetry.lock",
    "Gemfile.lock",
    "Cargo.lock",
    "composer.lock",
    "go.sum",
})